### ISSUE TITLE
Дополнительное выделение памяти

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-1_task-1#1]
https://github.com/tanya00pm/Homework-1_task-1/blob/6e7022fb01c7eb741af163c478ba23071c3ef4c2/BubbleSort.java#L12

Объявляя данную переменную, Вы используете дополнительное выделение памяти для изменения элементов в массиве)

**Comment by tanya00pm** [comment]
Исправлено, метод runBubbleIteration

**Comment by khda91** [comment]
closed
