### ISSUE TITLE
Java Naming convertion for methods

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-1_task-1#2]
https://github.com/tanya00pm/Homework-1_task-1/blob/6e7022fb01c7eb741af163c478ba23071c3ef4c2/BubbleSort.java#L9
https://github.com/tanya00pm/Homework-1_task-1/blob/6e7022fb01c7eb741af163c478ba23071c3ef4c2/BubbleSort.java#L26
https://github.com/tanya00pm/Homework-1_task-1/blob/6e7022fb01c7eb741af163c478ba23071c3ef4c2/BubbleSortApplication.java#L12

Обратите пожалуйста внимание на правила именования методов в Java.
https://drive.google.com/file/d/1psN0db7O4GT95OxudCCx1pV9igtq2ofY/view?usp=sharing

**Comment by tanya00pm** [comment]
поправлено )

**Comment by khda91** [comment]
closed
